"""
Exact preflop equity table (reader).

Loads the pre-computed exact equity table generated by
:mod:`poker_tool.scripts.generate_equity_table` and exposes per-pair lookups.

The table is a JSON file mapping ``"HeroHand|OppHand"`` -> ``{win, tie, lose}``
for all 169 x 169 canonical hand pairs (minus the impossible same-hand
pairings, e.g. AA vs AA). Values are exact (full board enumeration), so the
result is bit-identical on every load: no variance, no seed.

This object is a pure data reader: it loads the file once at construction and
serves lookups in O(1). It knows nothing about ranges or aggregation — that is
the responsibility of :class:`AggregateEquity`.
"""
import json
import os

# Default location: backend/data/equity_table.json
_DEFAULT_TABLE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__)
    ))),
    "data",
    "equity_table.json",
)


class EquityTable:
    """Reader for the exact preflop equity table."""

    def __init__(self, path: str | None = None) -> None:
        self._path = path or _DEFAULT_TABLE_PATH
        self._table: dict[str, dict] = self._load(self._path)

    @staticmethod
    def _load(path: str) -> dict[str, dict]:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Equity table not found at {path}. Generate it with "
                f"`python -m poker_tool.scripts.generate_equity_table`."
            )
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            raise ValueError(f"Invalid equity table format at {path}")
        return data

    @property
    def path(self) -> str:
        """Filesystem path of the loaded table."""
        return self._path

    @property
    def size(self) -> int:
        """Number of entries in the table."""
        return len(self._table)

    def lookup(self, hero: str, opp: str) -> dict | None:
        """Return {win, tie, lose} for a hero-vs-opp canonical pair.

        Returns ``None`` if the pairing is absent or impossible (e.g. AA vs AA).
        ``hero`` and ``opp`` are canonical notations (e.g. 'AKs', 'TT').
        """
        return self._table.get(f"{hero}|{opp}")

    def has(self, hero: str, opp: str) -> bool:
        """Whether the table holds the given hero-vs-opp pair."""
        return f"{hero}|{opp}" in self._table
