"""
Exact table equity calculator adapter (Elegant Objects).

Wraps the :class:`AggregateEquity` use case (instant O(1) aggregation over the
pre-computed exact equity table) behind the :class:`EquityCalculator` port.
This is the **default** strategy: bit-identical, reproducible equity with no
sampling variance, since the table is generated by exhaustive enumeration.

If the table is incomplete, ``compute`` raises :class:`MissingEquityEntry`
carrying the opponent hands absent from the table, so the HTTP layer can
return a 409 and let the frontend prompt the user to run a Monte-Carlo
simulation. The exact path never silently degrades to a high-variance
estimate; the Monte-Carlo engine is used only on explicit request.
"""
from ...interfaces.equity_calculator import EquityCalculator, MissingEquityEntry
from ...objects.equity import EquityResult
from ...use_cases.aggregate_equity import AggregateEquity


class TableEquityCalculator(EquityCalculator):
    """EquityCalculator backed by the exact pre-computed equity table."""

    def __init__(self, aggregate_equity: AggregateEquity) -> None:
        self._aggregate_equity = aggregate_equity

    def compute(
        self, hero: str, range_hands: list[str], iterations: int | None = None,
    ) -> EquityResult:
        """Aggregate exact table entries; raise MissingEquityEntry if any is absent.

        ``iterations`` is ignored: the exact path is deterministic.
        """
        missing = self._aggregate_equity.missing_entries(hero, range_hands)
        if missing:
            raise MissingEquityEntry(missing)
        return self._aggregate_equity.aggregate(hero, range_hands)
