"""
Exact table equity calculator adapter (Elegant Objects).

Wraps the :class:`AggregateEquity` use case (instant O(1) aggregation over the
pre-computed exact equity table) behind the :class:`EquityCalculator` port.
This is the **default** strategy: bit-identical, reproducible equity with no
sampling variance, since the table is generated by exhaustive enumeration.

If the table is missing or incomplete, :class:`AggregateEquity` raises a
:class:`ValueError`; this adapter lets that propagate so the fallback
composite (:mod:`adapters.equity.fallback`) can switch to Monte-Carlo.
"""
from ...interfaces.equity_calculator import EquityCalculator
from ...objects.equity import EquityResult
from ...use_cases.aggregate_equity import AggregateEquity


class TableEquityCalculator(EquityCalculator):
    """EquityCalculator backed by the exact pre-computed equity table."""

    def __init__(self, aggregate_equity: AggregateEquity) -> None:
        self._aggregate_equity = aggregate_equity

    def compute(self, hero: str, range_hands: list[str]) -> EquityResult:
        """Aggregate exact table entries; raises if any entry is missing."""
        return self._aggregate_equity.aggregate(hero, range_hands)
